### ISSUE TITLE
Speech data update is broken

### ISSUE THREAD

**Issue by dannydb** [nprapps/commencement#189]
```
$ fab data.update
https://docs.google.com/feeds/download/spreadsheets/Export?exportFormat=csv&key=1dDSs5QSEjieH-dWTnR7BVUxI2gH6EiUI0vfmmHMnMQU&gid=0
Start parse(): 52 rows.
Traceback (most recent call last):
  File "/Users/ddebelius/.virtualenvs/commencement/lib/python2.7/site-packages/fabric/main.py", line 717, in main
    *args, **kwargs
  File "/Users/ddebelius/.virtualenvs/commencement/lib/python2.7/site-packages/fabric/tasks.py", line 332, in execute
    results['<local-only>'] = task.run(*args, **new_kwargs)
  File "/Users/ddebelius/.virtualenvs/commencement/lib/python2.7/site-packages/fabric/tasks.py", line 112, in run
    return self.wrapped(*args, **kwargs)
  File "/Users/ddebelius/Projects/commencement/fabfile/data.py", line 22, in update
    update_data()
  File "/Users/ddebelius/.virtualenvs/commencement/lib/python2.7/site-packages/fabric/tasks.py", line 109, in __call__
    return self.run(*args, **kwargs)
  File "/Users/ddebelius/.virtualenvs/commencement/lib/python2.7/site-packages/fabric/tasks.py", line 112, in run
    return self.wrapped(*args, **kwargs)
  File "/Users/ddebelius/Projects/commencement/fabfile/data.py", line 30, in update_data
    commencement_data.parse()
  File "/Users/ddebelius/Projects/commencement/commencement_data.py", line 63, in parse
    row[k] = v.strip()
AttributeError: 'list' object has no attribute ‘strip’
```

**Comment by dannydb** [comment]
nevermind, it was an auth problem. Works now that I have edit permissions.
